### ISSUE TITLE
Helper class - PUT functions - possible to include Job Name parameter

### ISSUE THREAD

**Issue by stephenmcconnachie** [SpectraLogic/ds3_python3_sdk#54]
The Helper class is very useful and effective for managing bulk PUTs, but it doesn;t support one very useful operation - supplying a Name for the PUT Job.

This is supported in the Python SDK generally in the PutBulkJobSpectraS3Request, but it would be amazing to have it supported in the Helper version. 

Providing a name for each Job really helps with troubleshooting - for example in identifying network issues that are causing slow PUT progress. Naming the JOb for the network share is extremely effective in that troubleshooting process.

**Comment by RachelTucker** [comment]
The requested feature has been added in the latest release [v5.4.2](https://github.com/SpectraLogic/ds3_python3_sdk/releases/tag/v5.4.2).

**Comment by stephenmcconnachie** [comment]
Amazing, thank you
